name: Pythontest
on:
  push:
    branches: -main
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycryptodome
          
      - name: run test
        run: |
          cd ~
          cat << EOF > pythontest.py
          from Crypto.Hash import MD2
          txt = "39"
          for i in range(5):
            txt = MD2.new(txt.encode("utf8")).hexdigest()
            print(i)
            print(txt)
          EOF
          chmod +x pythontest.py
          python pythontest.py
